// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhtvhvkghnwdelmdxqtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpodHZodmtnaG53ZGVsbWR4cXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTM4MzMsImV4cCI6MjA2NzA4OTgzM30.SZEnK_uPrha-kr93ch4EUMjnqNr0sc1TF3S1Slh-kbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});